# Generated by Django 5.2.15 on 2026-07-02 15:04

import django.db.models.deletion
import engine.common.fields
import engine.telegram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "telegram_api_token",
                    engine.common.fields.EncryptedCharField(max_length=512),
                ),
                (
                    "webhook_secret",
                    engine.common.fields.EncryptedCharField(
                        default=engine.telegram.models.generate_webhook_secret,
                        help_text="Secret token sent as X-Telegram-Bot-Api-Secret-Token header",
                        max_length=64,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Is this bot active for message processing?",
                    ),
                ),
                (
                    "telegram_update_offset",
                    models.IntegerField(
                        default=0, help_text="Last processed Telegram update_id"
                    ),
                ),
                (
                    "webhook_enabled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the webhook was last successfully registered",
                        null=True,
                    ),
                ),
                (
                    "webhook_disabled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the webhook was last disabled (fallback to polling)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bot",
                "verbose_name_plural": "Bots",
                "db_table": "telegram_bot",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IntakeBuffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.CharField(max_length=255)),
                (
                    "reply_to_message_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("text", models.TextField()),
                ("message_count", models.PositiveIntegerField(default=1)),
                ("last_message_ts", models.PositiveBigIntegerField()),
                ("last_received_at", models.DateTimeField()),
                ("flushed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="telegram.bot"
                    ),
                ),
            ],
            options={
                "verbose_name": "Intake Buffer",
                "verbose_name_plural": "Intake Buffers",
                "db_table": "telegram_intakebuffer",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("flushed_at__isnull", True)),
                        fields=("bot", "chat_id"),
                        name="tg_uniq_open_intake_buffer_per_bot_chat",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reply_target", models.TextField()),
                (
                    "reply_to_message_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("raw_input", models.TextField()),
                ("raw_output", models.TextField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("llm_started_at", models.DateTimeField(blank=True, null=True)),
                ("llm_finished_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_started_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="telegram.bot"
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "db_table": "telegram_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        condition=models.Q(
                            ("error__isnull", True),
                            ("llm_finished_at__isnull", True),
                            ("llm_started_at__isnull", True),
                        ),
                        fields=["created_at", "id"],
                        name="tg_job_ready_llm_idx",
                    ),
                    models.Index(
                        condition=models.Q(
                            ("error__isnull", True),
                            ("llm_finished_at__isnull", True),
                            ("llm_started_at__isnull", False),
                        ),
                        fields=["llm_started_at"],
                        name="tg_job_stale_llm_idx",
                    ),
                    models.Index(
                        condition=models.Q(
                            ("delivery_finished_at__isnull", True),
                            ("delivery_started_at__isnull", True),
                            ("llm_finished_at__isnull", False),
                            models.Q(
                                ("raw_output__isnull", False),
                                ("error__isnull", False),
                                _connector="OR",
                            ),
                        ),
                        fields=["llm_finished_at", "id"],
                        name="tg_job_ready_delivery_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("raw_output__isnull", True),
                            ("llm_finished_at__isnull", False),
                            _connector="OR",
                        ),
                        name="tg_job_raw_output_requires_llm_finished",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("llm_finished_at__isnull", True),
                            ("raw_output__isnull", False),
                            ("error__isnull", False),
                            _connector="OR",
                        ),
                        name="tg_job_llm_finished_requires_result_or_error",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("delivery_started_at__isnull", True),
                            models.Q(
                                ("llm_finished_at__isnull", False),
                                models.Q(
                                    ("raw_output__isnull", False),
                                    ("error__isnull", False),
                                    _connector="OR",
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="tg_job_delivery_started_requires_output",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("delivery_finished_at__isnull", True),
                            ("delivery_started_at__isnull", False),
                            _connector="OR",
                        ),
                        name="tg_job_delivery_finished_requires_started",
                    ),
                ],
            },
        ),
    ]
