# Generated by Django 5.2.15 on 2026-07-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0002_migrate_data_from_legacy_tables"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="job",
            name="tg_job_raw_output_requires_llm_finished",
        ),
        migrations.RemoveConstraint(
            model_name="job",
            name="tg_job_llm_finished_requires_result_or_error",
        ),
        migrations.RemoveConstraint(
            model_name="job",
            name="tg_job_delivery_started_requires_output",
        ),
        migrations.RemoveIndex(
            model_name="job",
            name="tg_job_ready_llm_idx",
        ),
        migrations.RemoveIndex(
            model_name="job",
            name="tg_job_stale_llm_idx",
        ),
        migrations.RemoveIndex(
            model_name="job",
            name="tg_job_ready_delivery_idx",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="llm_finished_at",
            new_name="processing_finished_at",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="llm_started_at",
            new_name="processing_started_at",
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                condition=models.Q(
                    ("error__isnull", True),
                    ("processing_finished_at__isnull", True),
                    ("processing_started_at__isnull", True),
                ),
                fields=["created_at", "id"],
                name="tg_job_ready_processing_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                condition=models.Q(
                    ("error__isnull", True),
                    ("processing_finished_at__isnull", True),
                    ("processing_started_at__isnull", False),
                ),
                fields=["processing_started_at"],
                name="tg_job_stale_processing_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                condition=models.Q(
                    ("delivery_finished_at__isnull", True),
                    ("delivery_started_at__isnull", True),
                    ("processing_finished_at__isnull", False),
                    models.Q(
                        ("raw_output__isnull", False),
                        ("error__isnull", False),
                        _connector="OR",
                    ),
                ),
                fields=["processing_finished_at", "id"],
                name="tg_job_ready_delivery_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("raw_output__isnull", True),
                    ("processing_finished_at__isnull", False),
                    _connector="OR",
                ),
                name="tg_job_raw_output_requires_processing_finished",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("processing_finished_at__isnull", True),
                    ("raw_output__isnull", False),
                    ("error__isnull", False),
                    _connector="OR",
                ),
                name="tg_job_processing_finished_requires_result_or_error",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("delivery_started_at__isnull", True),
                    models.Q(
                        ("processing_finished_at__isnull", False),
                        models.Q(
                            ("raw_output__isnull", False),
                            ("error__isnull", False),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="tg_job_delivery_started_requires_output",
            ),
        ),
    ]
