# Generated by Codex on 2026-07-06

from django.db import migrations, models


def backfill_processing_started_at(apps, schema_editor):
    """Populate missing processing start timestamps before adding the constraint."""
    Job = apps.get_model("telegram", "Job")
    Job.objects.filter(
        processing_started_at__isnull=True,
        processing_finished_at__isnull=False,
    ).update(processing_started_at=models.F("processing_finished_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0004_update_q2_func_paths"),
    ]

    operations = [
        migrations.RunPython(
            backfill_processing_started_at,
            migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("processing_finished_at__isnull", True))
                    | models.Q(("processing_started_at__isnull", False))
                ),
                name="tg_job_processing_finished_requires_started",
            ),
        ),
    ]
