# Generated by Django 5.2.15 on 2026-06-25 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_target', models.TextField()),
                ('raw_input', models.TextField()),
                ('raw_output', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField()),
                ('llm_started_at', models.DateTimeField(blank=True, null=True)),
                ('llm_finished_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bots.bot')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-received_at'],
            },
        ),
    ]
