# Generated by Django 5.2.15 on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="reply_to_message_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
