# Generated by Django 5.2.15 on 2026-06-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_reply_to_message_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="received_at",
        ),
        migrations.AlterModelOptions(
            name="job",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
            },
        ),
    ]
