# Generated by Django 5.2.15 on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_remove_job_received_at_alter_job_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                condition=models.Q(
                    ("error__isnull", True),
                    ("llm_finished_at__isnull", True),
                    ("llm_started_at__isnull", True),
                ),
                fields=["created_at", "id"],
                name="job_ready_llm_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                condition=models.Q(
                    ("error__isnull", True),
                    ("llm_finished_at__isnull", True),
                    ("llm_started_at__isnull", False),
                ),
                fields=["llm_started_at"],
                name="job_stale_llm_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                condition=models.Q(
                    ("error__isnull", True),
                    ("llm_finished_at__isnull", False),
                    ("raw_output__isnull", False),
                    ("sent_at__isnull", True),
                ),
                fields=["-created_at", "id"],
                name="job_ready_delivery_idx",
            ),
        ),
    ]
