# Generated by Django 5.2.15 on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job_worker_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="delivery_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
