# Generated by Django 5.2.15 on 2026-06-27

from django.db import migrations, models


def backfill_delivery_started_at(apps, schema_editor):
    job_model = apps.get_model("jobs", "Job")
    job_model.objects.filter(
        sent_at__isnull=False,
        delivery_started_at__isnull=True,
    ).update(delivery_started_at=models.F("sent_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_job_delivery_started_at"),
    ]

    operations = [
        migrations.RunPython(
            backfill_delivery_started_at,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(raw_output__isnull=True)
                    | models.Q(llm_finished_at__isnull=False)
                ),
                name="job_raw_output_requires_llm_finished",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(llm_finished_at__isnull=True)
                    | models.Q(raw_output__isnull=False)
                    | models.Q(error__isnull=False)
                ),
                name="job_llm_finished_requires_result_or_error",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(delivery_started_at__isnull=True)
                    | (
                        models.Q(llm_finished_at__isnull=False)
                        & models.Q(raw_output__isnull=False)
                    )
                ),
                name="job_delivery_started_requires_output",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(sent_at__isnull=True)
                    | (
                        models.Q(delivery_started_at__isnull=False)
                        & models.Q(error__isnull=True)
                    )
                ),
                name="job_sent_requires_delivery_started_without_error",
            ),
        ),
    ]
