# Generated by Django 5.2.15 on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_backfill_delivery_started_at_and_job_constraints"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="job",
            name="job_sent_requires_delivery_started_without_error",
        ),
        migrations.RemoveIndex(
            model_name="job",
            name="job_ready_delivery_idx",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="sent_at",
            new_name="delivery_finished_at",
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                condition=models.Q(
                    delivery_finished_at__isnull=True,
                    error__isnull=True,
                    llm_finished_at__isnull=False,
                    raw_output__isnull=False,
                ),
                fields=["-created_at", "id"],
                name="job_ready_delivery_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(delivery_finished_at__isnull=True)
                    | (
                        models.Q(delivery_started_at__isnull=False)
                        & models.Q(error__isnull=True)
                    )
                ),
                name="job_delivery_finished_requires_started_without_error",
            ),
        ),
    ]
