# Generated by Django 5.2.15 on 2026-06-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0006_alter_bot_telegram_api_token"),
        ("jobs", "0007_rename_sent_at_to_delivery_finished_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="job",
            name="job_delivery_started_requires_output",
        ),
        migrations.RemoveConstraint(
            model_name="job",
            name="job_delivery_finished_requires_started_without_error",
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("delivery_started_at__isnull", True),
                    models.Q(
                        ("llm_finished_at__isnull", False),
                        models.Q(
                            ("raw_output__isnull", False),
                            ("error__isnull", False),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="job_delivery_started_requires_output",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("delivery_finished_at__isnull", True),
                    ("delivery_started_at__isnull", False),
                    _connector="OR",
                ),
                name="job_delivery_finished_requires_started",
            ),
        ),
    ]
