# Generated by Django 5.2.15 on 2026-06-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0006_alter_bot_telegram_api_token"),
        ("jobs", "0008_remove_job_job_delivery_started_requires_output_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="job",
            name="job_ready_delivery_idx",
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                condition=models.Q(
                    ("delivery_finished_at__isnull", True),
                    ("delivery_started_at__isnull", True),
                    ("llm_finished_at__isnull", False),
                    models.Q(
                        ("raw_output__isnull", False),
                        ("error__isnull", False),
                        _connector="OR",
                    ),
                ),
                fields=["llm_finished_at", "id"],
                name="job_ready_delivery_idx",
            ),
        ),
    ]
