# Generated by Django 5.2.15 on 2026-07-01 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0008_bot_webhook_secret"),
        ("jobs", "0009_remove_job_job_ready_delivery_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntakeBuffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.CharField(max_length=255)),
                (
                    "reply_to_message_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("text", models.TextField()),
                ("message_count", models.PositiveIntegerField(default=1)),
                ("last_message_at", models.DateTimeField()),
                ("flushed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bots.bot"
                    ),
                ),
            ],
            options={
                "verbose_name": "Intake Buffer",
                "verbose_name_plural": "Intake Buffers",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("flushed_at__isnull", True)),
                        fields=("bot", "chat_id"),
                        name="uniq_open_intake_buffer_per_bot_chat",
                    )
                ],
            },
        ),
    ]
