# Generated by Django 5.2.15 on 2026-07-01 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_intakebuffer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intakebuffer",
            name="last_message_at",
        ),
        migrations.AddField(
            model_name="intakebuffer",
            name="last_message_ts",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="intakebuffer",
            name="last_received_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
