# Generated by Django 5.2.15 on 2026-07-01 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0008_bot_webhook_secret"),
        ("inference", "0006_alter_provider_auth_token"),
        ("jobs", "0011_remove_intakebuffer_last_message_at_and_more"),
        ("library", "0004_alter_wrapper_skill_wrapper_unique_name_per_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intakebuffer",
            name="last_message_ts",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="intakebuffer",
            name="last_received_at",
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker",
                        to="bots.bot",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inference.profile",
                    ),
                ),
                (
                    "wrapper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="library.wrapper",
                    ),
                ),
            ],
            options={
                "verbose_name": "Worker",
                "verbose_name_plural": "Workers",
                "ordering": ["bot__name"],
            },
        ),
    ]
