# Generated by Django 5.2.15 on 2026-06-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0002_bot_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="telegram_update_offset",
            field=models.IntegerField(
                default=0, help_text="Last processed Telegram update_id"
            ),
        ),
    ]
