# Generated by Django 5.2.15 on 2026-06-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0003_bot_telegram_update_offset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bot",
            name="provider",
        ),
    ]
