# Generated by Django 5.2.15 on 2026-06-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0004_remove_bot_provider"),
        ("library", "0003_populate_wrapper_skill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bot",
            name="skill",
        ),
    ]
