# Generated by Django 5.2.15 on 2026-06-27 10:29

from django.db import migrations

import apps.common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0005_remove_bot_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="telegram_api_token",
            field=apps.common.fields.EncryptedCharField(max_length=512),
        ),
    ]
