# Generated by Django 5.2.15 on 2026-07-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0006_alter_bot_telegram_api_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="webhook_disabled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the webhook was last disabled (fallback to polling)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="webhook_enabled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the webhook was last successfully registered",
                null=True,
            ),
        ),
    ]
