# Generated by Django 5.2.15 on 2026-07-01 10:09

from django.db import migrations

import apps.bots.models
import apps.common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0007_bot_webhook_disabled_at_bot_webhook_enabled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="webhook_secret",
            field=apps.common.fields.EncryptedCharField(
                default=apps.bots.models.generate_webhook_secret,
                help_text="Secret token sent as X-Telegram-Bot-Api-Secret-Token header",
                max_length=64,
            ),
        ),
    ]
