# Generated by Django 5.2.15 on 2026-07-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0008_bot_webhook_secret"),
        ("jobs", "0013_populate_worker_from_bot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bot",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="bot",
            name="wrapper",
        ),
    ]
