# Generated by Django 5.2.15 on 2026-06-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="reasoning_summary",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="text_verbosity",
        ),
    ]
