# Generated by Django 5.2.15 on 2026-06-26 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0002_remove_profile_reasoning_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profiles",
                to="inference.provider",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(
                fields=("provider", "name"), name="unique_profile_name_per_provider"
            ),
        ),
    ]
