# Generated by Django 5.2.15 on 2026-06-26 09:15

from django.db import migrations


def assign_existing_profiles_to_provider(apps, _schema_editor):
    Profile = apps.get_model("inference", "Profile")
    Provider = apps.get_model("inference", "Provider")

    if not Profile.objects.filter(provider__isnull=True).exists():
        return

    providers = list(Provider.objects.all()[:2])
    if len(providers) != 1:
        raise RuntimeError(
            "Cannot migrate existing profiles automatically: expected exactly one "
            "provider to assign them to."
        )

    Profile.objects.filter(provider__isnull=True).update(provider=providers[0])


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0003_profile_provider_alter_profile_name_and_more"),
    ]

    operations = [
        migrations.RunPython(
            assign_existing_profiles_to_provider,
            migrations.RunPython.noop,
        ),
    ]
