# Generated by Django 5.2.15 on 2026-06-26 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0004_populate_profile_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profiles",
                to="inference.provider",
            ),
        ),
    ]
