# Generated by Django 5.2.15 on 2026-06-27 10:29

from django.db import migrations

import apps.common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0005_alter_profile_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="auth_token",
            field=apps.common.fields.EncryptedCharField(max_length=8192),
        ),
    ]
