"""Move Worker from apps.llm → apps.inference with table rename.

In production the ``llm_worker`` table already exists and is renamed to
``inference_worker``.  In fresh databases (test/CI) the table is created
from scratch.  The Django model state is registered under ``apps.inference``.
"""

from django.db import migrations, models
import django.db.models.deletion

_INFERENCE_WORKER_DDL = """
CREATE TABLE IF NOT EXISTS "inference_worker" (
    "id" BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "enabled" BOOLEAN NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
    "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
    "bot_id" BIGINT NOT NULL UNIQUE
        REFERENCES "telegram_bot"("id")
        DEFERRABLE INITIALLY DEFERRED,
    "profile_id" BIGINT NOT NULL
        REFERENCES "inference_profile"("id")
        DEFERRABLE INITIALLY DEFERRED,
    "wrapper_id" BIGINT NOT NULL
        REFERENCES "library_wrapper"("id")
        DEFERRABLE INITIALLY DEFERRED
);
"""


class Migration(migrations.Migration):
    """Move Worker model + physical table to ``apps.inference``."""

    dependencies = [
        ("inference", "0006_alter_provider_auth_token"),
        ("telegram", "0001_initial"),
        ("library", "0004_alter_wrapper_skill_wrapper_unique_name_per_skill"),
    ]

    state_operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker",
                        to="telegram.bot",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inference.profile",
                    ),
                ),
                (
                    "wrapper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="library.wrapper",
                    ),
                ),
            ],
            options={
                "ordering": ["bot__name"],
                "verbose_name": "Worker",
                "verbose_name_plural": "Workers",
                "db_table": "inference_worker",
            },
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "DO $$ BEGIN "
                "  IF EXISTS (SELECT FROM information_schema.tables "
                "    WHERE table_name = 'llm_worker') THEN "
                '    ALTER TABLE "llm_worker" RENAME TO "inference_worker"; '
                "  ELSE "
                f"    {_INFERENCE_WORKER_DDL} "
                "  END IF; "
                "END $$;"
            ),
            reverse_sql=migrations.RunSQL.noop,
            elidable=True,
        ),
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
    ]
