# Generated by Django 5.2.15 on 2026-07-02 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    replaces = [("worker", "0001_initial")]

    dependencies = [
        ("inference", "0006_alter_provider_auth_token"),
        ("library", "0004_alter_wrapper_skill_wrapper_unique_name_per_skill"),
        ("telegram", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker",
                        to="telegram.bot",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inference.profile",
                    ),
                ),
                (
                    "wrapper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="library.wrapper",
                    ),
                ),
            ],
            options={
                "verbose_name": "Worker",
                "verbose_name_plural": "Workers",
                "db_table": "worker_worker",
                "ordering": ["bot__name"],
            },
        ),
    ]
